version: '3.5'
services:
  client:
    container_name: client
    restart: always
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 8080:8080
    env_file: .env
    environment: 
      CLIENT_ENV: ${CLIENT_ENV}
    entrypoint: ["sh", "./client/scripts/start.sh"]
    volumes:
      - .:/client
      - yarn_cache:/client/node_modules
    networks:
      - app-network
  api:
    container_name: api
    restart: always
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    ports: 
      - "8000:8000"
    env_file: .env
    environment: 
      API_ENV: ${API_ENV}
    volumes:
      - ./api:/api
    depends_on:
      - db
    entrypoint: ["sh","./scripts/start.sh"]
    networks:
        - app-network

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=localhost
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
networks:
  app-network:
    external: true

volumes:
  yarn_cache:
  postgres_data:
