version: '3.5'
services:
  client:
    container_name: client
    restart: always
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - 8080:8080
    entrypoint: ["sh", "./client/scripts/start.sh"]
    volumes:
      - .:/client
      - yarn_cache:/client/node_modules
    networks:
      - app-network

networks:
  app-network:
    external: true

volumes:
  yarn_cache:
